#!/bin/sh

echo "pre-commit: Running pre-commit tests..."

# Aktywacja środowiska Conda
echo "pre-commit: Activating Conda environment gurobi_env..."
eval "$(/opt/anaconda3/bin/conda shell.bash hook)"
conda activate gurobi_env

echo "pre-commit: Setting source path variable."
export PYTHONPATH=$PYTHONPATH:$(pwd)/src

echo "pre-commit: Running code quality tests..."
flake8 .

FLAKE8_RESULT=$?

if [ $FLAKE8_RESULT -ne 0 ]; then
    echo "pre-commit: Code quality tests failed! Commit aborted. Please fix lint errors before committing."
    exit 1
fi

echo "pre-commit: Code quality tests passed! Proceeding with other tests..."

echo "pre-commit: Running unit tests..."
python -m unittest discover -s tests -p '*test.py'

RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo "pre-commit: Tests failed! Commit aborted. Please fix the errors before committing."
    exit 1
else
    echo "pre-commit: All tests passed. Proceeding with commit..."
    exit 0
fi