name: Project Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda and Install dependencies
        shell: bash
        run: |
          # Install Miniconda
          curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          eval "$($HOME/miniconda/bin/conda shell.bash hook)"
          conda init bash
          conda create -y -n testenv python=3.10 20
          conda activate testenv
          pip install -r requirements.txt

      - name: Code Quality Test
        shell: bash
        run: |
          eval "$($HOME/miniconda/bin/conda shell.bash hook)"
          conda activate testenv
          flake8 .
          if [ $? -eq 0 ]; then
              echo "Code quality check passed!"
          else
              echo "Code quality issues detected!"
              exit 1
          fi

      - name: Code Tests
        shell: bash
        run: |
          eval "$($HOME/miniconda/bin/conda shell.bash hook)"
          conda activate testenv
          export PYTHONPATH=src
          python -m unittest discover -s tests -p '*test.py'
          if [ $? -eq 0 ]; then
              echo "All tests passed!"
          else
              echo "Some tests failed!"
              exit 1
          fi